### PR TITLE
RMSRCBUILD-140 Build script helper function Parse-Version-From-ReleaseBranch incorrectly splits strings

### PR DESCRIPTION
**Pull request by raffaelfoidl**
https://re-motion.atlassian.net/browse/RMSRCBUILD-140

### CODE REVIEW

**Comment by raffaelfoidl** [comment]
The described problem seems to be related to the execution environment since `.NET Core 2.0` there is a `String.Split(String)` overload, which could explain why it worked sometimes/for someone. With the proposed change to use the `String.Split(String[], StringSplitOptions)` overload, it should work either way.

**Comment by MichaelKetting** [comment]
> The described problem seems to be related to the execution environment since starting with `.NET Core 2.0`, there is a `String.Split(String)` overload, which could explain why it worked sometimes/for someone. With the proposed change to use the `String.Split(String[], StringSplitOptions)` overload, it should work either way.

Nice find. Didn't think of that one.

**Review by Stefan-Ilic — APPROVED** [review]
It looks like the tests run on old Powershell 5 now too, so that must have been the error. Very nice job 👍

**Review by MichaelKetting — COMMENTED** [review]
I believe this bug was introduced after @Stefan-Ilic fround a bug in the split-logic when upgrading the original test suite. Was the test properly red before the fix?

**Comment by raffaelfoidl** [comment]
On PS 7.1, the test is green even before the fix. When running on 5.1, there apparently is made an implicit conversion from `"/v"` to `['/', 'v']`. This observation stems from the fact that, when inspecting `$SplitBranchname` with the debugger (input `"release/v1.2.3"`), its value is `["release", "", "1.2.3"]`. This then leads to an exception `Current branch name is not in a valid format (e. g. release/v1.2.3)` being thrown because `SplitBranchname` is not exactly of length 2. So yes, the new test was red before the fix (on PS 5.1).

**Comment by MichaelKetting** [comment]
@raffaelfoidl Said differently: we cannot ensure that this becomes invalid again but remain green if someone where to change the string.split call. For the test to become read, we would have to force the execution to be done with the powerhsell version used in the production scenario. We really should go and do this whole thing in c# ;)

**Review by MichaelKetting — APPROVED** [review]

**Pull request merged**
